# Build and test CifParser on both Windows and Linux
# If they succeed push to Nuget

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: WindowsBuildAndTest
  displayName: 'Windows build and test'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      configFilePath: 'GitVersion.yml'
      updateAssemblyInfo: true
  - script: dotnet restore
    displayName: Nuget restore
  - script: dotnet build /p:Version='$(GitVersion.NuGetVersion)'
    displayName: Build
  - script: dotnet test --no-build
    displayName: Unit Test
  - script: dotnet pack --no-build -o '$(build.artifactStagingDirectory)'
    displayName: Create Nuget package
- job: LinuxBuildAndTest
  displayName: 'Linux build and test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: dotnet restore
    displayName: Nuget restore
  - script: dotnet build
    displayName: Build
  - script: dotnet test
    displayName: Unit Test
- job: Publish
  displayName: 'Publish Nuget Package'
  pool:
    vmImage: 'windows-latest'
  dependsOn: 
  - WindowsBuildAndTest
  - LinuxBuildAndTest
  steps:
  - task: NuGetCommand@2
    inputs:
      command: push
      packagesToPush: '$(build.artifactStagingDirectory)/**/CifParser*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: NuGet
