# Build and test CifParser on both Windows and Linux
# If they succeed push to Nuget

trigger:
  - master

variables:
  buildConfiguration: 'Release'

jobs:
  - job: WindowsBuildAndTest
    displayName: 'Windows build and test'
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: UseDotNet@2
        displayName: Use .NET 6.0
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          configFilePath: 'GitVersion.yml'
      - script: dotnet build /p:Version=$(GitVersion.AssemblySemVer)
        displayName: Build
      - script: dotnet test --no-build
        displayName: Unit Test
      - script: dotnet pack CifParser/CifParser.csproj --no-build -o $(build.artifactStagingDirectory) -p:PackageVersion=$(GitVersion.NuGetVersion)
        displayName: Create Nuget package
      - publish: $(build.artifactStagingDirectory)
        artifact: CifParserPackage
  - job: LinuxBuildAndTest
    displayName: 'Linux build and test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName: Use .NET 6.0
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
      - script: dotnet build
        displayName: Build
      - script: dotnet test
        displayName: Unit Test
  - job: Publish
    displayName: 'Publish Nuget Package'
    pool:
      vmImage: 'windows-latest'
    dependsOn:
      - WindowsBuildAndTest
      - LinuxBuildAndTest
    steps:
      - download: current
        artifact: CifParserPackage
      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: '>=4.9.0'
          checkLatest: true
      - task: NuGetCommand@2
        inputs:
          command: push
          packagesToPush: $(Pipeline.Workspace)/**/CifParser*.nupkg
          nuGetFeedType: external
          publishFeedCredentials: NuGet
          includeSymbols: true